name: xc_web_admin
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  dio: ^5.4.0
  dropdown_button2: ^2.3.9
  fl_chart: ^0.60.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_svg: ^1.1.6
  get_it: ^7.6.7
  go_router: ^13.2.0
  google_fonts: ^4.0.4
  provider: ^6.1.0
  retrofit: ^4.0.3
  yandex_mapkit: ^3.4.0
  flutter_map: ^6.1.0
  google_maps: ^6.3.0
  latlong2: ^0.9.0
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/