// App pages
enum Pages {
  auth,
  adminMain, // separate window
  adminDashboard,
  adminUsers,
  adminClothes,
  adminShops,
  adminOrders,
  adminUserInfo, // separate window
  adminWeeklyActivityDetails,
  adminWeeklyItemsSoldDetails,
  adminAllUsers,
  adminAllActiveUsers,
  adminUserAddresses,
  adminShopAddressInfo,
  adminAllOrders,
  adminAllClothes,
  adminAllFemaleClothes,
  adminAllMaleClothes,
  adminOrderDetails, // separate window
  adminClothesDetails, // separate window
  adminAllColors,
  adminAllSizes,
  directorDashboard,
  directorShop,
  directorEmployees,
  directorClothes,
  directorAllClothes,
  directorAllFemaleClothes,
  directorAllMaleClothes,
  directorClothesDetails,
  directorWeeklyItemsSoldDetails, // separate window
  directorOrders,
  directorAllOrders,
  directorOrderDetails,
  employeeDashboard,
  employeeClothes,
  employeeOrders,
  employeeAllClothes,
  employeeAllFemaleClothes,
  employeeAllMaleClothes,
  employeeClothesDetails,
  employeeAllOrders,
  adminWeeklyOrdersDetails,
  directorWeeklyOrdersDetails,
  employeeWeeklyOrdersDetails
}

// Pages routes
extension AppPageExtension on Pages {
  String get screenPath {
    return switch (this) {
      Pages.auth => '/',
      Pages.adminMain => '/adminMain',
      Pages.adminDashboard => '/adminDashboard',
      Pages.adminUsers => '/adminUsers',
      Pages.adminClothes => '/adminClothes',
      Pages.adminShops => '/adminShops',
      Pages.adminOrders => '/adminOrders',
      Pages.adminUserInfo => '/adminUserInfo',
      Pages.adminWeeklyActivityDetails => '/adminWeeklyActivityDetails',
      Pages.adminAllUsers => '/adminAllUsers',
      Pages.adminAllActiveUsers => '/adminAllActiveUsers',
      Pages.adminUserAddresses => '/adminUserAddresses',
      Pages.adminShopAddressInfo => '/adminShopAddressInfo',
      Pages.adminAllOrders => '/adminAllOrders',
      Pages.adminAllClothes => '/adminAllClothes',
      Pages.adminAllFemaleClothes => '/adminAllFemaleClothes',
      Pages.adminAllMaleClothes => '/adminAllMaleClothes',
      Pages.adminOrderDetails => '/adminOrderDetails',
      Pages.adminClothesDetails => '/adminClothesDetails',
      Pages.directorDashboard => '/directorDashboard',
      Pages.employeeDashboard => '/employeeDashboard',
      Pages.directorShop => '/directorShop',
      Pages.directorEmployees => '/directorEmployees',
      Pages.directorClothes => '/directorClothes',
      Pages.directorAllClothes => '/directorAllClothes',
      Pages.directorClothesDetails => '/directorClothesDetails',
      Pages.directorOrders => '/directorOrders',
      Pages.directorAllOrders => '/directorAllOrders',
      Pages.directorOrderDetails => '/directorOrderDetails',
      Pages.adminAllColors => '/adminAllColors',
      Pages.adminAllSizes => '/adminAllSizes',
      Pages.adminWeeklyItemsSoldDetails => '/adminWeeklyItemsSoldDetails',
      Pages.directorWeeklyItemsSoldDetails => '/directorWeeklyItemsSoldDetails',
      Pages.employeeClothes => '/employeeClothes',
      Pages.employeeOrders => '/employeeOrders',
      Pages.employeeAllClothes => '/employeeAllClothes',
      Pages.employeeClothesDetails => '/employeeClothesDetails',
      Pages.employeeAllOrders => '/employeeAllOrders',
      Pages.adminWeeklyOrdersDetails => '/adminWeeklyOrdersDetails',
      Pages.directorWeeklyOrdersDetails => '/directorWeeklyOrdersDetails',
      Pages.employeeWeeklyOrdersDetails => '/employeeWeeklyOrdersDetails',
      Pages.directorAllFemaleClothes => '/directorAllFemaleClothes',
      Pages.directorAllMaleClothes => '/directorAllMaleClothes',
      Pages.employeeAllFemaleClothes => '/employeeAllFemaleClothes',
      Pages.employeeAllMaleClothes => '/employeeAllMaleClothes',
    };
  }

// Pages names
  String get screenName {
    return switch (this) {
      Pages.auth => 'auth',
      Pages.adminMain => 'adminMain',
      Pages.adminDashboard => 'adminDashboard',
      Pages.adminUsers => 'adminUsers',
      Pages.adminClothes => 'adminClothes',
      Pages.adminShops => 'adminShops',
      Pages.adminOrders => 'adminOrders',
      Pages.adminUserInfo => 'adminUserInfo',
      Pages.adminWeeklyActivityDetails => 'adminWeeklyActivityDetails',
      Pages.adminAllUsers => 'adminAllUsers',
      Pages.adminAllActiveUsers => 'adminAllActiveUsers',
      Pages.adminUserAddresses => 'adminUserAddresses',
      Pages.adminShopAddressInfo => 'adminShopAddressInfo',
      Pages.adminAllOrders => 'adminAllOrders',
      Pages.adminAllClothes => 'adminAllClothes',
      Pages.adminAllFemaleClothes => 'adminAllFemaleClothes',
      Pages.adminAllMaleClothes => 'adminAllMaleClothes',
      Pages.adminOrderDetails => 'adminOrderDetails',
      Pages.adminClothesDetails => 'adminClothesDetails',
      Pages.directorDashboard => 'directorDashboard',
      Pages.directorShop => 'directorShop',
      Pages.directorEmployees => 'directorEmployees',
      Pages.directorClothes => 'directorClothes',
      Pages.directorAllClothes => 'directorAllClothes',
      Pages.directorClothesDetails => 'directorClothesDetails',
      Pages.directorOrders => 'directorOrders',
      Pages.directorAllOrders => 'directorAllOrders',
      Pages.directorOrderDetails => 'directorOrderDetails',
      Pages.employeeDashboard => 'employeeDashboard',
      Pages.adminAllColors => 'adminAllColors',
      Pages.adminAllSizes => 'adminAllSizes',
      Pages.adminWeeklyItemsSoldDetails => 'adminWeeklyItemsSoldDetails',
      Pages.directorWeeklyItemsSoldDetails => 'directorWeeklyItemsSoldDetails',
      Pages.employeeClothes => 'employeeClothes',
      Pages.employeeOrders => 'employeeOrders',
      Pages.employeeAllClothes => 'employeeAllClothes',
      Pages.employeeClothesDetails => 'employeeClothesDetails',
      Pages.employeeAllOrders => 'employeeAllOrders',
      Pages.adminWeeklyOrdersDetails => 'adminWeeklyOrdersDetails',
      Pages.directorWeeklyOrdersDetails => 'directorWeeklyOrdersDetails',
      Pages.employeeWeeklyOrdersDetails => 'employeeWeeklyOrdersDetails',
      Pages.directorAllFemaleClothes => 'directorAllFemaleClothes',
      Pages.directorAllMaleClothes => 'directorAllMaleClothes',
      Pages.employeeAllFemaleClothes => 'employeeAllFemaleClothes',
      Pages.employeeAllMaleClothes => 'employeeAllMaleClothes',
    };
  }
}
